# Generated by Django 4.1.6 on 2023-02-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wingoapp', '0002_carreras_empresa_convenio_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(default='', help_text='Introduzca el correo electrónico del contacto', max_length=254, verbose_name='Correo Electrónico'),
        ),
    ]
