# Generated by Django 4.1.6 on 2023-02-27 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wingoapp', '0004_country_remove_empresa_paisempresa_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.ForeignKey(default=1, help_text='Seleccione el estado', on_delete=django.db.models.deletion.CASCADE, to='wingoapp.city', verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(default=1, help_text='Seleccione el país', on_delete=django.db.models.deletion.CASCADE, to='wingoapp.country', verbose_name='Pais'),
            preserve_default=False,
        ),
    ]
