# Generated by Django 4.1.6 on 2023-02-27 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wingoapp', '0005_empresa_estado_empresa_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.ForeignKey(help_text='Seleccione el estado', on_delete=django.db.models.deletion.CASCADE, to='wingoapp.city', verbose_name='Estado de la empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(help_text='Seleccione el país', on_delete=django.db.models.deletion.CASCADE, to='wingoapp.country', verbose_name='Pais de la empresa'),
        ),
    ]
