# Generated by Django 4.1.6 on 2023-02-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wingoapp', '0006_alter_empresa_estado_alter_empresa_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='pais',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
