# Generated by Django 4.1.6 on 2023-02-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wingoapp', '0007_remove_empresa_estado_remove_empresa_pais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wingoapp.country')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='city',
            field=models.ForeignKey(help_text='Seleccione el estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wingoapp.city', verbose_name='Estado de la empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='country',
            field=models.ForeignKey(help_text='Seleccione el país', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wingoapp.country', verbose_name='Pais de la empresa'),
        ),
    ]
