# Generated by Django 4.1.6 on 2023-03-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wingoapp', '0009_remove_empresa_city_remove_empresa_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='calle',
            field=models.CharField(default=None, help_text='Ingrese la calle donde está ubicada la empresa', max_length=200, verbose_name='Calle de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(default=None, help_text='Ingrese la ciudad donde está ubicada la empresa', max_length=200, verbose_name='Ciudad de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='colonia',
            field=models.CharField(default=None, help_text='Ingrese la colonia donde está ubicada la empresa', max_length=200, verbose_name='Colonia de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='cp',
            field=models.CharField(default=None, help_text='Ingrese el código postal de la empresa', max_length=5, verbose_name='Código postal de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(default=None, help_text='Ingrese el nombre conocido de la empresa', max_length=200, verbose_name='Nombre conocido de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(default=None, help_text='Ingrese el número del local donde está ubicada la empresa', max_length=10, verbose_name='Número de local de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='numeroInterior',
            field=models.CharField(default=None, help_text='Ingrese el número interior del local donde está ubicada la empresa', max_length=10, verbose_name='Número interior de la empresa'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
