# Generated by Django 4.1.6 on 2023-03-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wingoapp', '0010_empresa_calle_empresa_ciudad_empresa_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='finVigencia',
            field=models.DateField(verbose_name='Vigente hasta'),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='inicioVigencia',
            field=models.DateField(verbose_name='Vigente desde'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(blank=True, help_text='Ingrese el nombre conocido de la empresa', max_length=200, null=True, verbose_name='Nombre conocido de la empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numeroInterior',
            field=models.CharField(blank=True, help_text='Ingrese el número interior del local donde está ubicada la empresa', max_length=10, null=True, verbose_name='Número interior de la empresa'),
        ),
    ]
