# Generated by Django 4.1.6 on 2023-03-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wingoapp', '0011_alter_convenio_finvigencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(blank=True, default='None', help_text='Ingrese el nombre conocido de la empresa', max_length=200, null=True, verbose_name='Nombre conocido de la empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numeroInterior',
            field=models.CharField(blank=True, default='None', help_text='Ingrese el número interior del local donde está ubicada la empresa', max_length=10, null=True, verbose_name='Número interior de la empresa'),
        ),
    ]
