# Generated by Django 4.1.6 on 2023-03-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wingoapp', '0012_alter_empresa_nombre_alter_empresa_numerointerior'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del convenio'),
        ),
    ]
